repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
      - id: golangci-lint
  - repo: local
    hooks:
      - id: golines
        name: go lines
        description: Go line formatting
        entry: golines -w .
        language: golang
        pass_filenames: false
