source:
  format: "MONGODB"
  mongodb:
    url:
      secret_name: "projects/{{ .Project }}/secrets/mongodb-url/versions/latest"
    database: "testdb"
    collection: "events"
    filter: '{"timestamp": {"$gt": 1627783866000}}'
sink:
  format: "FILE"
  file:
    format: "PARQUET"
    path: "gs://{{ .Bucket }}/output/events.parquet"
