source:
  format: "FILE"
  file:
    format: "AVRO"
    path: "gs://{{ .Bucket }}/input/events.avro"
sink:
  format: "BIGQUERY"
  bigquery:
    project: "{{ .Project }}"
    dataset: "raw"
    table: "events"
