source:
  format: "BIGQUERY"
  bigquery:
    project: "{{ .Project }}"
    dataset: "raw"
    table: "events"
sink:
  format: "FILE"
  file:
    format: "CSV"
    path: "gs://{{ .Bucket }}/output/events.csv"
