source:
  format: "DATABASE"
  database:
    driver: "mysql"
    dsn:
      secret_name: "projects/{{ .Project }}/secrets/cloud-sql-dsn/versions/latest"
    table: "events"
sink:
  format: "ELASTICSEARCH"
  elasticsearch:
    cloud_id:
      secret_name: "projects/{{ .Project }}/secrets/elasticsearch-cloud-id/versions/latest"
    api_key:
      secret_name: "projects/{{ .Project }}/secrets/elasticsearch-api-key/versions/latest"
    index: "events"
