source:
  format: "FILE"
  file:
    format: "JSON"
    path: "gs://{{ .Bucket }}/input/events.json"
sink:
  format: "FILE"
  file:
    format: "PARQUET"
    path: "gs://{{ .Bucket }}/output/events.parquet"
