source:
  format: "FILE"
  file:
    format: "PARQUET"
    path: "gs://{{ .Bucket }}/input/events.parquet"
sink:
  format: "REDIS"
  redis:
    url:
      secret: "projects/{{ .Project }}/secrets/redis-url/versions/latest"
    key_field: "EventId"
