source:
  format: "FILE"
  file:
    format: "CSV"
    path: "gs://{{ .Bucket }}/input/events.csv"
sink:
  format: "DATABASE"
  database:
    driver: "mysql"
    dsn:
      secret_name: "projects/{{ .Project }}/secrets/cloud-sql-dsn/versions/latest"
    table: "events"
