source:
  format: "BIGQUERY"
  bigquery:
    project: "{{ .Project }}"
    table: "{{ .Project }}:raw.users"
sink:
  format: "FIRESTORE"
  firestore:
    project: "{{ .Project }}"
    collection: "users"
