source:
  format: "FILE"
  file:
    format: "AVRO"
    path: "gs://{{ .Bucket }}/input/users.avro"
sink:
  format: "BIGQUERY"
  bigquery:
    project: "{{ .Project }}"
    table: "{{ .Project }}:raw.users"
