source:
  format: "REDIS"
  redis:
    url:
      secret: "projects/{{ .Project }}/secrets/redis-url/versions/latest"
    key_patterns:
      - "*"
sink:
  format: "FILE"
  file:
    format: "JSON"
    path: "gs://{{ .Bucket }}/output/users.json"
