source:
  format: "BIGQUERY"
  bigquery:
    project: "{{ .Project }}"
    dataset: "raw"
    table: "users"
sink:
  format: "FIRESTORE"
  firestore:
    project: "{{ .Project }}"
    collection: "users"
