source:
  format: "BIGQUERY"
  bigquery:
    project: "{{ .Project }}"
    table: "{{ .Project }}:raw.users"
sink:
  format: "FILE"
  file:
    format: "AVRO"
    path: "gs://{{ .Bucket }}/output/users.avro"
    avro:
      schema: '{
        "type": "record",
        "name": "Users",
        "fields": [
            {"name": "id", "type": "int"},
            {"name": "first_name", "type": "string"},
            {"name": "last_name", "type": "string"},
            {"name": "email", "type": "string"}
        ]
      }'
